stages:
  prepare_data:
    cmd: python src/prepare_data.py
    deps:
      - src/prepare_data.py
      - params.yaml
      - data/cifar100.npz
    outs:
      - data/processed_data.npz

  train_MobileNetV2:
    cmd: python src/train_MobileNetV2.py
    deps:
      - src/train_MobileNetV2.py
      - params.yaml
      - data/processed_data.npz
    outs:
      - models/MobileNetV2_bf_ft.keras
      - models/MobileNetV2_ft.keras
    metrics:
      - metrics/train_MobileNetV2_bf_ft_metrics.json
      - metrics/train_MobileNetV2_ft_metrics.json

  evaluate_MobileNetV2:
    cmd: python src/evaluate_MobileNetV2.py
    deps:
      - src/evaluate_MobileNetV2.py
      - models/MobileNetV2_ft.keras
      - data/processed_data.npz
    outs:
      - plots/confusion_MobileNetV2.png
    metrics:
      - metrics/classification_report_MobileNetV2.json
      - metrics/evaluate_MobileNetV2_metrics.json

